/*******************************************************************************
 * CLI - A simple command line interface.
 * Copyright (C) 2013 Daniele Pallastrelli
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

#include <iostream>
#include <string>
#include "cli.h"

// ###################################################

void Show( int x )
{
    std::cout << "Show: " << x << std::endl;
}

void Dump( void )
{
    std::cout << "Dump" << std::endl;
}

class Application
{
public:
    void Start()
    {
        std::cout << "Application::Start" << std::endl;
    }
    void Stop()
    {
        std::cout << "Application::Stop" << std::endl;
    }
    void Run( int x )
    {
        std::cout << "Application::Run: " << x << std::endl;
    }
};

// ###################################################

int main()
{
    Application app;

    using namespace boost;
    using namespace cli;

    Cli cli;
        
    Menu rootMenu( &cli, "root" );
 
    Menu statusMenu( &cli, &rootMenu, "status" );
    statusMenu.Add( new FuncCmd( "dump", Dump ) );
    statusMenu.Add( new FuncCmd1< int >( "show", bind( Show, _1 ) ) );

    Menu cmdMenu( &cli, &rootMenu, "cmd" );
    cmdMenu.Add( new FuncCmd( "stop", bind( &Application::Stop, &app ) ) );
    cmdMenu.Add( new FuncCmd( "start", bind( &Application::Start, &app ) ) );
    cmdMenu.Add( new FuncCmd1< int >( "run", bind( &Application::Run, &app, _1 ) ) );
    
    rootMenu.Add( &statusMenu );
    rootMenu.Add( &cmdMenu );
    
    cli.Current( &rootMenu );
    cli.Run();
    
    return 0;
}
